### ISSUE TITLE
problems starting a project

### ISSUE THREAD

**Issue by matvey1111** [badpocyk/PassportDetection#1]
Здравствуйте, возникла проблема с запуском из-за  new_image = Image.fromarray(augment(aug,np.array(image))), augment не объявлен. Буду рад любой документации к проекту.

**Comment by badpocyk** [comment]
> Здравствуйте, возникла проблема с запуском из-за new_image = Image.fromarray(augment(aug,np.array(image))), augment не объявлен. Буду рад любой документации к проекту.

Обновил ячейку
